/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TaiKhoan;

import BUS.bus_TaiKhoan;
import DTO.TaiKhoanValidateException;
import DTO.TaiKhoanDTO;
import java.awt.Window;
import javax.swing.JOptionPane;

public class FormSuaTaiKhoan extends javax.swing.JDialog {

    private AfterSuaTaiKhoan afterSuaNhanVien;
    private TaiKhoanDTO defaultNhanVienDTO;

    public FormSuaTaiKhoan() {
        super();
        initComponents();
    }

    public FormSuaTaiKhoan(Window owner, ModalityType modalityType) {
        super(owner, modalityType);
        initComponents();
    }

    public AfterSuaTaiKhoan getAfterSuaNhanVien() {
        return afterSuaNhanVien;
    }

    public void setAfterSuaTaiKhoan(AfterSuaTaiKhoan afterSuaTaiKhoan) {
        this.afterSuaNhanVien = afterSuaTaiKhoan;
    }

    public void clearAfterSuaNhanVien() {
        this.afterSuaNhanVien = null;
    }

    public TaiKhoanDTO getDefaultNhanVienDTO() {
        return defaultNhanVienDTO;
    }

    public void setDefaultNhanVienDTO(TaiKhoanDTO defaultNhanVienDTO) {
        this.defaultNhanVienDTO = defaultNhanVienDTO;
    }

    public void setDefaultInformations(TaiKhoanDTO nhanVienDTO) {
        this.textfeildHoTen.setText(this.defaultNhanVienDTO.getHO_TEN());
        this.textfeilTenDangNhap.setText(this.defaultNhanVienDTO.getTEN_DANG_NHAP());
        this.textfeildSDT.setText(this.defaultNhanVienDTO.getSDT());
        this.passwordfeildMatKhau.setText(this.defaultNhanVienDTO.getMAT_KHAU());
        this.comboboxLoaiNhanVien.setSelectedIndex(this.defaultNhanVienDTO.getLOAI());
    }

    public TaiKhoanDTO parseInformation() {
        TaiKhoanDTO nhanVienDTO = null;

        nhanVienDTO = new TaiKhoanDTO(
                this.defaultNhanVienDTO.getMA_NV(),
                this.textfeildHoTen.getText(),
                this.textfeildSDT.getText(),
                this.comboboxLoaiNhanVien.getSelectedIndex(),
                this.textfeilTenDangNhap.getText(),
                String.valueOf(this.passwordfeildMatKhau.getPassword())
        );

        return nhanVienDTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneSuaNhanVien = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfeildHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfeildSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboboxLoaiNhanVien = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textfeilTenDangNhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordfeildMatKhau = new javax.swing.JPasswordField();
        buttonXacNhan = new javax.swing.JButton();
        buttonReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập Nhật Tài Khoản");
        setResizable(false);

        paneSuaNhanVien.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("CẬP NHẬT");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("TÊN NHÂN VIÊN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("SỐ ĐIỆN THOẠI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("LOẠI NHÂN VIÊN");

        comboboxLoaiNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Ghi danh", "Học vụ" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("TÊN ĐĂNG NHẬP");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("MẬT KHẨU");

        buttonXacNhan.setBackground(new java.awt.Color(91, 155, 213));
        buttonXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        buttonXacNhan.setText("Okie");
        buttonXacNhan.setContentAreaFilled(false);
        buttonXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXacNhan.setFocusable(false);
        buttonXacNhan.setOpaque(true);
        buttonXacNhan.setPreferredSize(new java.awt.Dimension(209, 40));
        buttonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXacNhanActionPerformed(evt);
            }
        });

        buttonReset.setBackground(new java.awt.Color(91, 155, 213));
        buttonReset.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonReset.setForeground(new java.awt.Color(255, 255, 255));
        buttonReset.setText("Reset");
        buttonReset.setContentAreaFilled(false);
        buttonReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonReset.setFocusable(false);
        buttonReset.setOpaque(true);
        buttonReset.setPreferredSize(new java.awt.Dimension(209, 40));
        buttonReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneSuaNhanVienLayout = new javax.swing.GroupLayout(paneSuaNhanVien);
        paneSuaNhanVien.setLayout(paneSuaNhanVienLayout);
        paneSuaNhanVienLayout.setHorizontalGroup(
            paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSuaNhanVienLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(167, 167, 167))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneSuaNhanVienLayout.createSequentialGroup()
                        .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6))))
                        .addGap(38, 38, 38)
                        .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                                .addComponent(comboboxLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(textfeildHoTen)
                                    .addComponent(textfeildSDT)
                                    .addComponent(textfeilTenDangNhap)
                                    .addComponent(passwordfeildMatKhau))
                                .addGap(97, 97, 97))))))
            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(buttonXacNhan, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addGap(56, 56, 56)
                .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(81, 81, 81))
        );
        paneSuaNhanVienLayout.setVerticalGroup(
            paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfeildHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(paneSuaNhanVienLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textfeildSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboboxLoaiNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfeilTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordfeildMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(paneSuaNhanVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonReset, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneSuaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneSuaNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXacNhanActionPerformed
        //Tiến hành sửa tài khoản 
        TaiKhoanDTO newNhanVienDTO = this.parseInformation();

        if (newNhanVienDTO.equals(this.defaultNhanVienDTO)) {
            JOptionPane.showMessageDialog(
                    this,
                    "Bạn chưa sửa thông tin tài khoản",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        int deleteResult = JOptionPane.showConfirmDialog(this,
                "Bạn có chắc chắn muốn sửa thông tin tài khoản " + newNhanVienDTO.getMA_NV() + ":\n"
                + "Tên tài khoản: '" + this.defaultNhanVienDTO.getHO_TEN() + "'   ➠   '" + newNhanVienDTO.getHO_TEN() + "'" + "\n"
                + "Số điện thoại: '" + this.defaultNhanVienDTO.getSDT() + "'   ➠   '" + newNhanVienDTO.getSDT() + "'" + "\n"
                + "Loại tài khoản: '" + this.defaultNhanVienDTO.getLOAIToString() + "'   ➠   '" + newNhanVienDTO.getLOAIToString() + "'" + "\n"
                + "Tên đăng nhập: '" + this.defaultNhanVienDTO.getTEN_DANG_NHAP() + "'   ➠   '" + newNhanVienDTO.getTEN_DANG_NHAP() + "'" + "\n"
                + "Mật khẩu: '" + this.defaultNhanVienDTO.getMAT_KHAU() + "'   ➠   '" + newNhanVienDTO.getMAT_KHAU() + "'" + "\n",
                "Sủa thông tin tài khoản",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );

        if (deleteResult == JOptionPane.YES_OPTION) {
            //Sửa ngay và luôn 
            boolean suaResult;
            try {
                suaResult = bus_TaiKhoan.getInstance().suaNhanVien(defaultNhanVienDTO, newNhanVienDTO);
                String messageResults = "Sửa tài khoản " + newNhanVienDTO.getMA_NV() + " - " + newNhanVienDTO.getHO_TEN() + " " + (suaResult ? "thành công" : "thất bại");
                JOptionPane.showMessageDialog(this, messageResults, "Kết quả sửa tài khoản", JOptionPane.INFORMATION_MESSAGE);
            } catch (TaiKhoanValidateException ex) {
                String messageResults = "Sửa tài khoản " + newNhanVienDTO.getMA_NV() + " - " + newNhanVienDTO.getHO_TEN() + " " + "thất bại do " + ex.getMessage();
                JOptionPane.showMessageDialog(this, messageResults, "Kết quả sửa tài khoản", JOptionPane.INFORMATION_MESSAGE);
            }

        } else if (deleteResult == JOptionPane.NO_OPTION) {
            return;
        }

        //Làm việc sau khi sửa 
        if (this.afterSuaNhanVien != null) {
            this.afterSuaNhanVien.DoAfterSuaTaiKhoan();
        }
    }//GEN-LAST:event_buttonXacNhanActionPerformed

    private void buttonResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonResetActionPerformed
        this.setDefaultInformations(this.defaultNhanVienDTO);
    }//GEN-LAST:event_buttonResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormSuaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormSuaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormSuaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormSuaTaiKhoan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormSuaTaiKhoan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonReset;
    private javax.swing.JButton buttonXacNhan;
    private javax.swing.JComboBox<String> comboboxLoaiNhanVien;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel paneSuaNhanVien;
    private javax.swing.JPasswordField passwordfeildMatKhau;
    private javax.swing.JTextField textfeilTenDangNhap;
    private javax.swing.JTextField textfeildHoTen;
    private javax.swing.JTextField textfeildSDT;
    // End of variables declaration//GEN-END:variables
}
