/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.TaiKhoan;

/**
 *
 * @author USER
 */
public class UI_TaiKhoan extends javax.swing.JPanel {

    /**
     * Creates new form UI_TaiKhoan
     */
    public UI_TaiKhoan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCapNhatTK = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtTimTK = new javax.swing.JTextField();
        btnThemTK = new javax.swing.JButton();
        jspKH = new javax.swing.JScrollPane();
        tbTK = new javax.swing.JTable();
        btnXoaTK = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 620));

        btnCapNhatTK.setBackground(new java.awt.Color(255, 255, 255));
        btnCapNhatTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapNhatTK.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capnhat.png"))); // NOI18N
        btnCapNhatTK.setContentAreaFilled(false);
        btnCapNhatTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhatTK.setFocusable(false);
        btnCapNhatTK.setMaximumSize(new java.awt.Dimension(129, 49));
        btnCapNhatTK.setMinimumSize(new java.awt.Dimension(129, 49));
        btnCapNhatTK.setOpaque(true);
        btnCapNhatTK.setPreferredSize(new java.awt.Dimension(129, 49));
        btnCapNhatTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatTKActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Tìm Kiếm");

        txtTimTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimTK.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimTK.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));
        txtTimTK.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtTimTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimTKActionPerformed(evt);
            }
        });

        btnThemTK.setBackground(new java.awt.Color(255, 255, 255));
        btnThemTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemTK.setForeground(new java.awt.Color(255, 255, 255));
        btnThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taomoi.png"))); // NOI18N
        btnThemTK.setContentAreaFilled(false);
        btnThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemTK.setFocusable(false);
        btnThemTK.setMaximumSize(new java.awt.Dimension(217, 60));
        btnThemTK.setMinimumSize(new java.awt.Dimension(217, 60));
        btnThemTK.setOpaque(true);
        btnThemTK.setPreferredSize(new java.awt.Dimension(209, 30));
        btnThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemTKActionPerformed(evt);
            }
        });

        jspKH.setBackground(new java.awt.Color(255, 255, 255));
        jspKH.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspKH.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspKH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jspKH.setPreferredSize(new java.awt.Dimension(469, 200));
        jspKH.setViewportView(null);

        tbTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tbTK.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "a", null, null, null, null, null, null},
                {null, "2", "a", null, null, null, null, null, null},
                {null, "3", "a", null, null, null, null, null, null},
                {null, "4", "a", null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã KH", "Họ Tên", "Ngày Sinh", "Giới Tính", "Điện Thoại", "Địa Chỉ", "Trạng Thái", "Điểm Đầu Vào"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbTK.setFocusable(false);
        tbTK.setPreferredSize(new java.awt.Dimension(600, 450));
        tbTK.setRowHeight(30);
        tbTK.setRowMargin(5);
        tbTK.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tbTK.setShowGrid(true);
        jspKH.setViewportView(tbTK);

        btnXoaTK.setBackground(new java.awt.Color(255, 255, 255));
        btnXoaTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaTK.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnXoaTK.setToolTipText("");
        btnXoaTK.setContentAreaFilled(false);
        btnXoaTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaTK.setFocusable(false);
        btnXoaTK.setMaximumSize(new java.awt.Dimension(129, 49));
        btnXoaTK.setMinimumSize(new java.awt.Dimension(129, 49));
        btnXoaTK.setOpaque(true);
        btnXoaTK.setPreferredSize(new java.awt.Dimension(129, 49));
        btnXoaTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaTKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addGap(50, 50, 50)
                        .addComponent(txtTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jspKH, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnXoaTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhatTK, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(10, 10, 10)))
                .addComponent(jspKH, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatTKActionPerformed
    }//GEN-LAST:event_btnCapNhatTKActionPerformed

    private void txtTimTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimTKActionPerformed

    private void btnThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemTKActionPerformed
    }//GEN-LAST:event_btnThemTKActionPerformed

    private void btnXoaTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaTKActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaTKActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatTK;
    private javax.swing.JButton btnThemTK;
    private javax.swing.JButton btnXoaTK;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jspKH;
    private javax.swing.JTable tbTK;
    private javax.swing.JTextField txtTimTK;
    // End of variables declaration//GEN-END:variables
}
