/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.QuanLyNhanVien;

import BUS.NhanVienBUS;
import DAL.dal_DangNhap;
import DTO.NhanVienDTO;
import DTO.dto_DangNhap;
import java.awt.Frame;
import javax.swing.JOptionPane;

public class FormThemNhanVien extends javax.swing.JDialog {

    private AfterThemNhanVien afterThemNhanVien;

    /**
     * Creates new form FormThemNhanVien
     */
    public FormThemNhanVien() {
        initComponents();
        this.afterThemNhanVien = null;
    }

    public FormThemNhanVien(Frame owner) {
        super(owner);
    }

    public AfterThemNhanVien getAfterThemTaiKhoan() {
        return afterThemNhanVien;
    }

    public void setAfterThemNhanVien(AfterThemNhanVien afterThemNhanVien) {
        this.afterThemNhanVien = afterThemNhanVien;
    }

    public void ClearAfterThemTaiKhoan() {
        this.afterThemNhanVien = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnThemTK = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textfeildTenNhanVien = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textfeildSDT = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        comboxLoai = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        textfieldTenDangNhap = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        passwordFeild = new javax.swing.JPasswordField();
        buttonXacNhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo Tài Khoản");

        pnThemTK.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TẠO MỚI");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("TÊN NHÂN VIÊN");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("SỐ ĐIỆN THOẠI");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("LOẠI NHÂN VIÊN");

        comboxLoai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Quản lý", "Ghi danh", "Học vụ" }));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("TÊN ĐĂNG NHẬP");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("MẬT KHẨU");

        buttonXacNhan.setBackground(new java.awt.Color(91, 155, 213));
        buttonXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        buttonXacNhan.setText("XÁC NHẬN");
        buttonXacNhan.setContentAreaFilled(false);
        buttonXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXacNhan.setFocusable(false);
        buttonXacNhan.setOpaque(true);
        buttonXacNhan.setPreferredSize(new java.awt.Dimension(209, 40));
        buttonXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXacNhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnThemTKLayout = new javax.swing.GroupLayout(pnThemTK);
        pnThemTK.setLayout(pnThemTKLayout);
        pnThemTKLayout.setHorizontalGroup(
            pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemTKLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(pnThemTKLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))))
                .addGap(38, 38, 38)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textfeildTenNhanVien)
                    .addComponent(textfeildSDT)
                    .addComponent(comboxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfieldTenDangNhap)
                    .addComponent(passwordFeild, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE))
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemTKLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemTKLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnThemTKLayout.createSequentialGroup()
                        .addComponent(buttonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(145, 145, 145))))
        );
        pnThemTKLayout.setVerticalGroup(
            pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnThemTKLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textfeildTenNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnThemTKLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3))
                    .addGroup(pnThemTKLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(textfeildSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxLoai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textfieldTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnThemTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(buttonXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXacNhanActionPerformed
        //Làm gì đó thêm nhân viên
        NhanVienDTO newNhanVienDTO = new NhanVienDTO(
                null,
                this.textfeildTenNhanVien.getText(),
                this.textfeildSDT.getText(),
                this.comboxLoai.getSelectedIndex(),
                this.textfieldTenDangNhap.getText(),
                new String(this.passwordFeild.getPassword())
        );

        boolean themResult = NhanVienBUS.getInstance().themNhanVien(newNhanVienDTO);
        String messageResults = "Thêm nhân viên " + newNhanVienDTO.getHO_TEN() + " " + (themResult ? "thành công" : "thất bại");
        JOptionPane.showMessageDialog(this, messageResults, "Kết quả thêm nhân viên", JOptionPane.INFORMATION_MESSAGE);

        //Sau đó làm phần AfterThem
        if (this.afterThemNhanVien != null) {
            this.afterThemNhanVien.DoAfterThemNhanVien();
        }
    }//GEN-LAST:event_buttonXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThemNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThemNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonXacNhan;
    private javax.swing.JComboBox<String> comboxLoai;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField passwordFeild;
    private javax.swing.JPanel pnThemTK;
    private javax.swing.JTextField textfeildSDT;
    private javax.swing.JTextField textfeildTenNhanVien;
    private javax.swing.JTextField textfieldTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
