/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.QuanLyNhanVien;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author caonguyen
 */
public final class UI_QuanLyNhanVIen_New extends javax.swing.JPanel {

    private final NhanVienTableModel nhanVienTableModel = new NhanVienTableModel();

    /**
     * Creates new form UI_QuanLyNhanVIen_New
     */
    public UI_QuanLyNhanVIen_New() {
        this.initComponents();
        this.initializeLookAndFeels();
        this.initializeEvents();

        this.refreshDataInTable();
    }

    public void initializeLookAndFeels() {
        this.buttonLamMoi.setBorder(new CustomCompoundBorder(2, 0));
        CustomComponentModify.getInstance().modifyButton(this.buttonLamMoi, CustomComponentModify.buttonType.OUTLINE_DARK, new Font("Noto", Font.PLAIN, 24));

        this.buttonSua.setBorder(new CustomCompoundBorder(2, 0));
        CustomComponentModify.getInstance().modifyButton(this.buttonSua, CustomComponentModify.buttonType.OUTLINE_INFO, new Font("Noto", Font.PLAIN, 24));

        this.buttonThem.setBorder(new CustomCompoundBorder(2, 0));
        CustomComponentModify.getInstance().modifyButton(this.buttonThem, CustomComponentModify.buttonType.OUTLINE_PRIMARY, new Font("Noto", Font.PLAIN, 24));

        this.buttonXoa.setBorder(new CustomCompoundBorder(2, 0));
        CustomComponentModify.getInstance().modifyButton(this.buttonXoa, CustomComponentModify.buttonType.OUTLINE_DANGER, new Font("Noto", Font.PLAIN, 24));

        this.buttonStopSearch.setBorder(new CustomCompoundBorder(2, 10));
        CustomComponentModify.getInstance().modifyButton(this.buttonStopSearch, CustomComponentModify.buttonType.DARK, new Font("Noto", Font.PLAIN, 16));

        this.textfieldTuKhoa.setBorder(new CustomCompoundBorder(1, 10));
        this.textfieldTuKhoa.setFont(new Font("Noto", Font.PLAIN, 16));

        this.labelTimKiem.setFont(new Font("Noto", Font.PLAIN, 16));

        this.tableNhanVien.setFont(new Font("Noto", Font.PLAIN, 16));
        this.tableNhanVien.getTableHeader().setFont(new Font("Noto", Font.BOLD, 18));
        this.tableNhanVien.getTableHeader().setForeground(CustomComponentModify.DARK);
        this.tableNhanVien.setSelectionBackground(new Color(0, 0, 0, 100));
        this.tableNhanVien.setModel(this.nhanVienTableModel);
        //Tính thêm padding cho cell mà lười nên thôi
    }

    public void initializeEvents() {
        this.buttonStopSearch.setVisible(false);

        this.textfieldTuKhoa.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent arg0) {
                ChangeFilter();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                ChangeFilter();
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                ChangeFilter();
            }

            public void ChangeFilter() {
                String keyword = textfieldTuKhoa.getText();
                if (keyword.isEmpty()) {
                    buttonStopSearch.setVisible(false);
                    nhanVienTableModel.UpdataInTable();
                } else {
                    buttonStopSearch.setVisible(true);
                    nhanVienTableModel.FilterNhanVienDTO(keyword);
                }
            }
        });
    }

    public NhanVienTableModel getNhanVienTableModel() {
        return nhanVienTableModel;
    }

    public void refreshDataInTable() {
        this.nhanVienTableModel.setNhanVienDTOs(NhanVienBUS.getInstance().getDanhSachNhanVien());
        this.nhanVienTableModel.UpdataInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTimKiem = new javax.swing.JLabel();
        textfieldTuKhoa = new javax.swing.JTextField();
        buttonStopSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        buttonThem = new javax.swing.JButton();
        buttonXoa = new javax.swing.JButton();
        buttonSua = new javax.swing.JButton();
        buttonLamMoi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNhanVien = new javax.swing.JTable();

        jPanel1.setPreferredSize(new java.awt.Dimension(1067, 678));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.setPreferredSize(new java.awt.Dimension(297, 70));

        labelTimKiem.setText("Tìm kiếm");

        buttonStopSearch.setText("✕");
        buttonStopSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(labelTimKiem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textfieldTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonStopSearch)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textfieldTuKhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStopSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(0, 0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(70, 58));

        buttonThem.setText("⊕");
        buttonThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemActionPerformed(evt);
            }
        });

        buttonXoa.setText("⊖");
        buttonXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaActionPerformed(evt);
            }
        });

        buttonSua.setText("∗");
        buttonSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSuaActionPerformed(evt);
            }
        });

        buttonLamMoi.setText("🗘");
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(buttonSua, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                        .addComponent(buttonXoa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonThem, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonThem, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSua, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        tableNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        tableNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tableNhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 979, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1061, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 594, Short.MAX_VALUE))
                .addGap(8, 8, 8))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStopSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopSearchActionPerformed
        this.textfieldTuKhoa.setText("");
        this.nhanVienTableModel.UpdataInTable();
        this.buttonStopSearch.setVisible(false);
    }//GEN-LAST:event_buttonStopSearchActionPerformed

    private void buttonThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemActionPerformed
        FormThemNhanVien formThemNhanVien = new FormThemNhanVien();

        formThemNhanVien.setAfterThemNhanVien(new AfterThemNhanVien() {
            @Override
            public void DoAfterThemNhanVien() {
                refreshDataInTable();
            }
        });

        formThemNhanVien.setLocationRelativeTo(this);
        formThemNhanVien.setVisible(true);
        formThemNhanVien.show();
    }//GEN-LAST:event_buttonThemActionPerformed

    private void buttonXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaActionPerformed
        int[] rowSelecteds = this.tableNhanVien.getSelectedRows();

        if (rowSelecteds.length < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Hãy chọn ít nhất một nhân viên trước khi nhấn nút",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel defaultTableModel = (DefaultTableModel) this.tableNhanVien.getModel();

        String deletedNhanVienDTOInfos = "";
        ArrayList<NhanVienDTO> deletedNhanVienDTOs = new ArrayList<>();
        for (int rowSelected : rowSelecteds) {
            NhanVienDTO deletedNhanVienDTO = new NhanVienDTO().fromVector(defaultTableModel.getDataVector().get(rowSelected));
            deletedNhanVienDTOs.add(deletedNhanVienDTO);
            deletedNhanVienDTOInfos += deletedNhanVienDTO.toString();
            deletedNhanVienDTOInfos += "\n";
        }

        int deleteChooseResult = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xoá " + rowSelecteds.length + " nhân viên không? "
                + "\n"
                + "Thông tin" + (rowSelecteds.length > 1 ? " các" : "") + " nhân viên đó là: "
                + "\n"
                + deletedNhanVienDTOInfos,
                "Xóa nhân viên",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );

        if (deleteChooseResult == JOptionPane.YES_OPTION) {
            //Xoá ngay và luôn 
String messageResults = "";            
            for (NhanVienDTO deletedNhanVienDTO : deletedNhanVienDTOs) {
                boolean deleteResult = NhanVienBUS.getInstance().xoaNhanVien(deletedNhanVienDTO);
                messageResults += "Xóa nhân viên " + deletedNhanVienDTO.getMA_NV() + " - " + deletedNhanVienDTO.getHO_TEN() + " " + (deleteResult ? "thành công" : "thất bại");
                messageResults += "\n";
            }
            JOptionPane.showMessageDialog(this, messageResults, "Kết quả xóa nhân viên", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_buttonXoaActionPerformed

    private void buttonSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSuaActionPerformed
        int rowSelected = this.tableNhanVien.getSelectedRow();

        if (rowSelected < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Hãy chọn một nhân viên trước khi nhấn nút",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        FormSuaNhanVien formCapNhatNhanVien = new FormSuaNhanVien();

        DefaultTableModel defaultTableModel = (DefaultTableModel) this.tableNhanVien.getModel();
        NhanVienDTO nhanVienDTO = new NhanVienDTO();
        nhanVienDTO.fromVector(defaultTableModel.getDataVector().get(rowSelected));
        formCapNhatNhanVien.setDefaultNhanVienDTO(nhanVienDTO);
        formCapNhatNhanVien.setDefaultInformations(nhanVienDTO);

        formCapNhatNhanVien.setAfterSuaNhanVien(new AfterSuaNhanVien() {
            @Override
            public void DoAfterSuaNhanVien() {
                refreshDataInTable();
            }
        });

        formCapNhatNhanVien.show();
    }//GEN-LAST:event_buttonSuaActionPerformed

    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        this.refreshDataInTable();
    }//GEN-LAST:event_buttonLamMoiActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JButton buttonStopSearch;
    private javax.swing.JButton buttonSua;
    private javax.swing.JButton buttonThem;
    private javax.swing.JButton buttonXoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelTimKiem;
    private javax.swing.JTable tableNhanVien;
    private javax.swing.JTextField textfieldTuKhoa;
    // End of variables declaration//GEN-END:variables
}
