/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.QuanLyNhanVien;

import BUS.NhanVienBUS;
import DTO.NhanVienDTO;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

public class UI_QuanlyNhanVien extends javax.swing.JPanel {

    private final NhanVienTableModel nhanVienTableModel = new NhanVienTableModel();

    /**
     * Creates new form FormTaiKhoanUI
     */
    public UI_QuanlyNhanVien() {
        initComponents();

        this.tableTaiKhoan.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        this.tableTaiKhoan.getTableHeader().setOpaque(false);
        this.tableTaiKhoan.getTableHeader().setForeground(new Color(22, 105, 158));
        this.tableTaiKhoan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        this.tableTaiKhoan.setModel(this.nhanVienTableModel);

        this.buttonStopSearch.setVisible(false);
        
        this.textfeildTimTK.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent arg0) {
                ChangeFilter();
            }

            @Override
            public void removeUpdate(DocumentEvent arg0) {
                 ChangeFilter();
            }

            @Override
            public void changedUpdate(DocumentEvent arg0) {
                 ChangeFilter();
            }
            
            public void ChangeFilter() {
                String keyword = textfeildTimTK.getText();
                if (keyword.isEmpty()) {
                     buttonStopSearch.setVisible(false);
                     nhanVienTableModel.UpdataInTable();
                 }
                else {
                    buttonStopSearch.setVisible(true);
                    nhanVienTableModel.FilterNhanVienDTO(keyword);
                }
            }
        });
    }

    public NhanVienTableModel getNhanVienTableModel() {
        return nhanVienTableModel;
    }

    public void refreshDataInTable() {
        this.nhanVienTableModel.setNhanVienDTOs(NhanVienBUS.getInstance().getDanhSachNhanVien());
        this.nhanVienTableModel.UpdataInTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paneChuongTrinh = new javax.swing.JPanel();
        labelTimLop = new javax.swing.JLabel();
        textfeildTimTK = new javax.swing.JTextField();
        buttonThemTK = new javax.swing.JButton();
        scrollpaneLH = new javax.swing.JScrollPane();
        tableTaiKhoan = new javax.swing.JTable();
        buttonXoaNhanVien = new javax.swing.JButton();
        buttonCapNhatNhanVien = new javax.swing.JButton();
        buttonLamMoi = new javax.swing.JButton();
        buttonStopSearch = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 659));

        paneChuongTrinh.setBackground(new java.awt.Color(255, 255, 255));

        labelTimLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTimLop.setForeground(new java.awt.Color(0, 0, 0));
        labelTimLop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTimLop.setText("TÌM NHÂN VIÊN");

        textfeildTimTK.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        textfeildTimTK.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        textfeildTimTK.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        buttonThemTK.setBackground(new java.awt.Color(239, 158, 154));
        buttonThemTK.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonThemTK.setForeground(new java.awt.Color(0, 0, 0));
        buttonThemTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/them lop.png"))); // NOI18N
        buttonThemTK.setText("TẠO NHÂN VIÊN MỚI");
        buttonThemTK.setContentAreaFilled(false);
        buttonThemTK.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonThemTK.setFocusable(false);
        buttonThemTK.setOpaque(true);
        buttonThemTK.setPreferredSize(new java.awt.Dimension(183, 40));
        buttonThemTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonThemTKActionPerformed(evt);
            }
        });

        scrollpaneLH.setBackground(new java.awt.Color(255, 255, 255));
        scrollpaneLH.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollpaneLH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        scrollpaneLH.setPreferredSize(new java.awt.Dimension(469, 400));

        tableTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tableTaiKhoan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableTaiKhoan.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableTaiKhoan.setDoubleBuffered(true);
        tableTaiKhoan.setFocusable(false);
        tableTaiKhoan.setPreferredSize(new java.awt.Dimension(600, 450));
        tableTaiKhoan.setRowHeight(30);
        tableTaiKhoan.setSelectionBackground(new java.awt.Color(204, 204, 204));
        tableTaiKhoan.setShowGrid(true);
        tableTaiKhoan.getTableHeader().setReorderingAllowed(false);
        scrollpaneLH.setViewportView(tableTaiKhoan);

        buttonXoaNhanVien.setBackground(new java.awt.Color(91, 155, 213));
        buttonXoaNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonXoaNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        buttonXoaNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        buttonXoaNhanVien.setText("XÓA");
        buttonXoaNhanVien.setContentAreaFilled(false);
        buttonXoaNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonXoaNhanVien.setFocusable(false);
        buttonXoaNhanVien.setMaximumSize(new java.awt.Dimension(129, 49));
        buttonXoaNhanVien.setMinimumSize(new java.awt.Dimension(129, 49));
        buttonXoaNhanVien.setOpaque(true);
        buttonXoaNhanVien.setPreferredSize(new java.awt.Dimension(129, 49));
        buttonXoaNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonXoaNhanVienActionPerformed(evt);
            }
        });

        buttonCapNhatNhanVien.setBackground(new java.awt.Color(239, 158, 154));
        buttonCapNhatNhanVien.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonCapNhatNhanVien.setForeground(new java.awt.Color(0, 0, 0));
        buttonCapNhatNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cap nhat 1.png"))); // NOI18N
        buttonCapNhatNhanVien.setText("CẬP NHẬT");
        buttonCapNhatNhanVien.setContentAreaFilled(false);
        buttonCapNhatNhanVien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonCapNhatNhanVien.setFocusable(false);
        buttonCapNhatNhanVien.setMaximumSize(new java.awt.Dimension(129, 49));
        buttonCapNhatNhanVien.setMinimumSize(new java.awt.Dimension(129, 49));
        buttonCapNhatNhanVien.setOpaque(true);
        buttonCapNhatNhanVien.setPreferredSize(new java.awt.Dimension(129, 49));
        buttonCapNhatNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCapNhatNhanVienActionPerformed(evt);
            }
        });

        buttonLamMoi.setBackground(new java.awt.Color(91, 155, 213));
        buttonLamMoi.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonLamMoi.setForeground(new java.awt.Color(0, 0, 0));
        buttonLamMoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        buttonLamMoi.setText("LÀM MỚI");
        buttonLamMoi.setContentAreaFilled(false);
        buttonLamMoi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonLamMoi.setFocusable(false);
        buttonLamMoi.setMaximumSize(new java.awt.Dimension(129, 49));
        buttonLamMoi.setMinimumSize(new java.awt.Dimension(129, 49));
        buttonLamMoi.setOpaque(true);
        buttonLamMoi.setPreferredSize(new java.awt.Dimension(129, 49));
        buttonLamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLamMoiActionPerformed(evt);
            }
        });

        buttonStopSearch.setBackground(new java.awt.Color(237, 209, 203));
        buttonStopSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buttonStopSearch.setForeground(new java.awt.Color(0, 0, 0));
        buttonStopSearch.setText("✕");
        buttonStopSearch.setContentAreaFilled(false);
        buttonStopSearch.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonStopSearch.setFocusable(false);
        buttonStopSearch.setOpaque(true);
        buttonStopSearch.setPreferredSize(new java.awt.Dimension(183, 40));
        buttonStopSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStopSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneChuongTrinhLayout = new javax.swing.GroupLayout(paneChuongTrinh);
        paneChuongTrinh.setLayout(paneChuongTrinhLayout);
        paneChuongTrinhLayout.setHorizontalGroup(
            paneChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChuongTrinhLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(paneChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollpaneLH, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paneChuongTrinhLayout.createSequentialGroup()
                        .addComponent(labelTimLop)
                        .addGap(18, 18, 18)
                        .addComponent(textfeildTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonStopSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonCapNhatNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        paneChuongTrinhLayout.setVerticalGroup(
            paneChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneChuongTrinhLayout.createSequentialGroup()
                .addGroup(paneChuongTrinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textfeildTimTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonThemTK, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCapNhatNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonXoaNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonLamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStopSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(scrollpaneLH, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(192, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(paneChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonThemTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonThemTKActionPerformed
        FormThemNhanVien formThemNhanVien = new FormThemNhanVien();

        formThemNhanVien.setAfterThemTaiKhoan(new AfterThemNhanVien() {
            @Override
            public void DoAfterThemTaiKhoan() {
                refreshDataInTable();
            }
        });

        formThemNhanVien.show();
    }//GEN-LAST:event_buttonThemTKActionPerformed

    private void buttonXoaNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonXoaNhanVienActionPerformed

        int[] rowSelecteds = this.tableTaiKhoan.getSelectedRows();

        if (rowSelecteds.length < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Hãy chọn ít nhất một nhân viên trước khi nhấn nút",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        DefaultTableModel defaultTableModel = (DefaultTableModel) this.tableTaiKhoan.getModel();

        String deletedNhanVienDTOInfos = "";
        for (int rowSelected : rowSelecteds) {
            deletedNhanVienDTOInfos += new NhanVienDTO().fromVector(defaultTableModel.getDataVector().get(rowSelected)).toString();
            deletedNhanVienDTOInfos += "\n";
        }

        int deleteResult = JOptionPane.showConfirmDialog(
                this,
                "Bạn có chắc chắn muốn xoá " + rowSelecteds.length + " nhân viên không? "
                + "\n"
                + "Thông tin" + (rowSelecteds.length > 1 ? " các" : "") + " nhân viên đó là: "
                + "\n"
                + deletedNhanVienDTOInfos,
                "Xóa nhân viên",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.INFORMATION_MESSAGE
        );

        if (deleteResult == JOptionPane.YES_OPTION) {
            //Xoá ngay và luôn 
        }
    }//GEN-LAST:event_buttonXoaNhanVienActionPerformed

    private void buttonCapNhatNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCapNhatNhanVienActionPerformed
        int rowSelected = this.tableTaiKhoan.getSelectedRow();

        if (rowSelected < 0) {
            JOptionPane.showMessageDialog(
                    this,
                    "Hãy chọn một nhân viên trước khi nhấn nút",
                    "Thông báo",
                    JOptionPane.ERROR_MESSAGE
            );
            return;
        }

        FormCapNhatNhanVien formCapNhatNhanVien = new FormCapNhatNhanVien();

        DefaultTableModel defaultTableModel = (DefaultTableModel) this.tableTaiKhoan.getModel();
        NhanVienDTO nhanVienDTO = new NhanVienDTO();
        nhanVienDTO.fromVector(defaultTableModel.getDataVector().get(rowSelected));
        formCapNhatNhanVien.setDefaultInformations(nhanVienDTO);

        formCapNhatNhanVien.setAfterSuaNhanVien(new AfterSuaNhanVien() {
            @Override
            public void DoAfterSuaNhanVien() {
                refreshDataInTable();
            }
        });

        formCapNhatNhanVien.show();
    }//GEN-LAST:event_buttonCapNhatNhanVienActionPerformed

    private void buttonLamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLamMoiActionPerformed
        this.refreshDataInTable();
    }//GEN-LAST:event_buttonLamMoiActionPerformed

    private void buttonStopSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStopSearchActionPerformed
        this.textfeildTimTK.setText("");
        this.nhanVienTableModel.UpdataInTable();
        this.buttonStopSearch.setVisible(false);
    }//GEN-LAST:event_buttonStopSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCapNhatNhanVien;
    private javax.swing.JButton buttonLamMoi;
    private javax.swing.JButton buttonStopSearch;
    private javax.swing.JButton buttonThemTK;
    private javax.swing.JButton buttonXoaNhanVien;
    private javax.swing.JLabel labelTimLop;
    private javax.swing.JPanel paneChuongTrinh;
    private javax.swing.JScrollPane scrollpaneLH;
    private javax.swing.JTable tableTaiKhoan;
    private javax.swing.JTextField textfeildTimTK;
    // End of variables declaration//GEN-END:variables
}
