/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LopHocUI.ChiTietLopHoc;

import BUS.bus_ChiTietLop;
import DTO.dto_ChiTiet_KH;
import DTO.dto_KhachHang;
import static UI.LopHocUI.ChiTietLopHoc.UI_ChiTietLop.dtmChiTiet;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinkPro
 */
public class FormThemVaoLop extends JDialog {

    /**
     * Creates new form FormThemVaoLop
     */
    public FormThemVaoLop() {
        initComponents();
        setupThongTin();
        layGiaTriNhap();
        //new bus_ChiTietLop().dsTimKH("N");

    }
    /*Khu vực của Tân*/
    
    static DefaultTableModel static_dtmThemVaoLop = new DefaultTableModel();
    static ArrayList<dto_KhachHang> static_dsKhachHang = new ArrayList<dto_KhachHang>();
    String txt ="";
    bus_ChiTietLop bus_ctl = new bus_ChiTietLop();
    
    
    // Setup thông tin
    public void setupThongTin(){
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setupTable();
    }
    
    // Reload Table
    public static void static_reloadTable(ArrayList<dto_KhachHang> list){
        static_dsKhachHang = list;
        
        static_dtmThemVaoLop.setRowCount(0);
        int stt = 0;
        
        if(list != null){

            for(dto_KhachHang kh : list){
                stt++;
                Vector<Object> vc = new Vector<Object>();
                vc.add(stt);
                vc.add(kh.getMaKH());
                vc.add(kh.getHoTen());
                vc.add(kh.getGioiTinh());
                vc.add(kh.getNgaySinh());
                vc.add(kh.getSdt());
                
                if(kh.getTrangThai() == 0)
                    vc.add("Chưa có");
                else
                    vc.add("Đã có");
                
                static_dtmThemVaoLop.addRow(vc);
            }
        }   
    }
    
    // Setup Bảng: Tạo column - setModel - chỉnh độ rộng cột - chỉnh màu.
    public  void setupTable(){

        static_dtmThemVaoLop.addColumn("STT");
        static_dtmThemVaoLop.addColumn("Mã KH");
        static_dtmThemVaoLop.addColumn("Họ Tên");
        static_dtmThemVaoLop.addColumn("Giới Tính");
        static_dtmThemVaoLop.addColumn("Ngày Sinh");
        static_dtmThemVaoLop.addColumn("Điện Thoại");
        //static_dtmThemVaoLop.addColumn("Địa Chỉ");
        static_dtmThemVaoLop.addColumn("Lớp hiện tại");
        
        tbThemVaoLop.setModel(static_dtmThemVaoLop);
        
        tbThemVaoLop.getColumnModel().getColumn(0).setMaxWidth(50);
	tbThemVaoLop.getColumnModel().getColumn(1).setMinWidth(50);
	tbThemVaoLop.getColumnModel().getColumn(2).setMinWidth(150);
	tbThemVaoLop.getColumnModel().getColumn(3).setMinWidth(50);
	tbThemVaoLop.getColumnModel().getColumn(4).setMinWidth(50);
	tbThemVaoLop.getColumnModel().getColumn(5).setMinWidth(50);
        
        tbThemVaoLop.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        tbThemVaoLop.getTableHeader().setOpaque(false);
        tbThemVaoLop.getTableHeader().setForeground(new Color(22, 105, 158));
        tbThemVaoLop.setSelectionBackground(new Color(204,204,204));   
    }
    
    // Event keyRealeas: Khi gõ vào khung tìm kiếm
    private void layGiaTriNhap(){
       txt = txtTimKH.getText();
       bus_ctl.dsTimKH(txt);
       
    }
    // Event btnXacNhanThem Lấy thông tin dòng được chọn trong cửa sổ Thêm vào lớp 
    private void layGiaTriDong(){ 
        int row = tbThemVaoLop.getSelectedRow();
        
        if(row >= 0){
            
            dto_KhachHang kh = static_dsKhachHang.get(row);
            
            
        }
        else{
            JOptionPane.showMessageDialog(null, "Chưa chọn khách hàng");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTimKH = new javax.swing.JTextField();
        scThemVaoLop = new javax.swing.JScrollPane();
        tbThemVaoLop = new javax.swing.JTable();
        btnXacNhanThem = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Thêm Vào Lớp");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TÌM KIẾM KHÁCH HÀNG");

        txtTimKH.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimKH.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(0, 0, 0)));
        txtTimKH.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKHKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTimKHKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTimKHKeyTyped(evt);
            }
        });

        tbThemVaoLop.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbThemVaoLop.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã KH", "Họ Tên", "Giới Tính", "Điện Thoại", "Địa Chỉ", "Lớp Hiện Tại"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbThemVaoLop.setPreferredSize(new java.awt.Dimension(600, 400));
        tbThemVaoLop.setRowHeight(30);
        tbThemVaoLop.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        scThemVaoLop.setViewportView(tbThemVaoLop);
        if (tbThemVaoLop.getColumnModel().getColumnCount() > 0) {
            tbThemVaoLop.getColumnModel().getColumn(0).setMaxWidth(100);
            tbThemVaoLop.getColumnModel().getColumn(1).setMinWidth(150);
            tbThemVaoLop.getColumnModel().getColumn(1).setMaxWidth(150);
            tbThemVaoLop.getColumnModel().getColumn(2).setMaxWidth(100);
            tbThemVaoLop.getColumnModel().getColumn(3).setMaxWidth(100);
            tbThemVaoLop.getColumnModel().getColumn(5).setMinWidth(150);
            tbThemVaoLop.getColumnModel().getColumn(5).setMaxWidth(200);
        }

        btnXacNhanThem.setBackground(new java.awt.Color(91, 155, 213));
        btnXacNhanThem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhanThem.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhanThem.setText("XÁC NHẬN");
        btnXacNhanThem.setContentAreaFilled(false);
        btnXacNhanThem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhanThem.setFocusable(false);
        btnXacNhanThem.setOpaque(true);
        btnXacNhanThem.setPreferredSize(new java.awt.Dimension(209, 40));
        btnXacNhanThem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnXacNhanThemMouseClicked(evt);
            }
        });
        btnXacNhanThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanThemActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("THÊM VÀO LỚP HỌC");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1)
                        .addGap(34, 34, 34)
                        .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(scThemVaoLop, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnXacNhanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(349, 349, 349))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(354, 354, 354))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKH, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scThemVaoLop, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(btnXacNhanThem, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanThemActionPerformed
        ArrayList<dto_ChiTiet_KH> list = new ArrayList<dto_ChiTiet_KH>();
        dto_ChiTiet_KH ct1 = new dto_ChiTiet_KH(10, "Test");
        list.add(ct1);
        
        UI_ChiTietLop.reloadTable(list);
        
    }//GEN-LAST:event_btnXacNhanThemActionPerformed

    private void txtTimKHKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKHKeyTyped

    }//GEN-LAST:event_txtTimKHKeyTyped

    private void txtTimKHKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKHKeyPressed

    }//GEN-LAST:event_txtTimKHKeyPressed
    
        
    private void txtTimKHKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKHKeyReleased
             layGiaTriNhap();
    }//GEN-LAST:event_txtTimKHKeyReleased

    private void btnXacNhanThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnXacNhanThemMouseClicked
        layGiaTriDong();
    }//GEN-LAST:event_btnXacNhanThemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormThemVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormThemVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormThemVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormThemVaoLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormThemVaoLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhanThem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane scThemVaoLop;
    private javax.swing.JTable tbThemVaoLop;
    private javax.swing.JTextField txtTimKH;
    // End of variables declaration//GEN-END:variables
}
