/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LopHocUI.ChiTietLopHoc;

import BUS.bus_ChiTiet;
import DTO.dto_ChiTiet;
import DTO.dto_LopHoc;
import UI.LopHocUI.ChiTietLopHoc.FormThemVaoLop;
import UI.LopHocUI.FormCapNhatLH;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinkPro
 */
public class UI_ChiTietLop extends javax.swing.JFrame {

    /**
     * Creates new form FormLichSuLH
     */
    public UI_ChiTietLop() {
        initComponents();
        setupTable();
        requestReloadTable();
    }

    /**
     * Khu vực của Tân
     */
    
    static dto_LopHoc dto_lop = new dto_LopHoc(1);
    static bus_ChiTiet bus_chiTiet =  new bus_ChiTiet();
    static DefaultTableModel dtmChiTiet  = new DefaultTableModel();
    static int stt = 0;
    
    // Hàm truyền Mã lớp yêu cầu bus lấy dữ liệu đẩy lên bảng
    public void requestReloadTable(){
        bus_chiTiet.getListChiTietLop(dto_lop);
    }
    
    // Hàm đẩy dữ liệu lên bảng - được gọi từ lớp bus.
    public static void reloadTable(ArrayList<dto_ChiTiet> listChiTiet){
        stt = 0;
        dtmChiTiet.setRowCount(0);
        for(dto_ChiTiet ct : listChiTiet){
            stt++;
            Vector<Object> vc = new Vector<Object>();
            
            vc.add(stt);
            vc.add(ct.getMa());
            vc.add(ct.getHoTen());
            vc.add(ct.getGioiTinh());
            vc.add(ct.getSdt());
            vc.add(ct.getNghe());
            vc.add(ct.getNoi());
            vc.add(ct.getDoc());
            vc.add(ct.getViet());
            vc.add(ct.getTb());
            dtmChiTiet.addRow(vc);
        }
    }
    
    // Setup Bảng: Tạo column - setModel - chỉnh độ rộng cột - chỉnh màu.
    public void setupTable(){

        dtmChiTiet.addColumn("STT");
        dtmChiTiet.addColumn("Mã KH");
        dtmChiTiet.addColumn("Họ Tên");
        dtmChiTiet.addColumn("Giới Tính");
        dtmChiTiet.addColumn("Điện Thoại");
        dtmChiTiet.addColumn("Nghe");
        dtmChiTiet.addColumn("Nói");
        dtmChiTiet.addColumn("Đọc");
        dtmChiTiet.addColumn("Viết");
        dtmChiTiet.addColumn("Trung Bình");
           
        tbChiTiet.setModel(dtmChiTiet);
        
        tbChiTiet.getColumnModel().getColumn(0).setMaxWidth(50);
	tbChiTiet.getColumnModel().getColumn(1).setMinWidth(80);
	tbChiTiet.getColumnModel().getColumn(2).setMinWidth(150);
	tbChiTiet.getColumnModel().getColumn(4).setMinWidth(100);
        
        tbChiTiet.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        tbChiTiet.getTableHeader().setOpaque(false);
        tbChiTiet.getTableHeader().setForeground(new Color(22, 105, 158));
        tbChiTiet.setSelectionBackground(new Color(204,204,204));
    }
    
    //----------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLop = new javax.swing.JPanel();
        btnThemLop = new javax.swing.JButton();
        jspLH = new javax.swing.JScrollPane();
        tbChiTiet = new javax.swing.JTable(dtmChiTiet);
        btnChiTietLop = new javax.swing.JButton();
        btnXoaLop = new javax.swing.JButton();
        btnUpdateLop = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CHI TIẾT LỚP HỌC");
        setResizable(false);

        pnLop.setBackground(new java.awt.Color(255, 255, 255));

        btnThemLop.setBackground(new java.awt.Color(91, 155, 213));
        btnThemLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLop.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/them lop.png"))); // NOI18N
        btnThemLop.setText("THÊM VÀO LỚP");
        btnThemLop.setContentAreaFilled(false);
        btnThemLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemLop.setFocusable(false);
        btnThemLop.setOpaque(true);
        btnThemLop.setPreferredSize(new java.awt.Dimension(183, 40));
        btnThemLop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThemLopMouseClicked(evt);
            }
        });
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });

        jspLH.setBackground(new java.awt.Color(255, 255, 255));
        jspLH.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspLH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jspLH.setPreferredSize(new java.awt.Dimension(450, 400));

        tbChiTiet.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbChiTiet.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbChiTiet.setDoubleBuffered(true);
        tbChiTiet.setFocusable(false);
        tbChiTiet.setPreferredSize(new java.awt.Dimension(600, 450));
        tbChiTiet.setRowHeight(30);
        tbChiTiet.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbChiTiet.getTableHeader().setReorderingAllowed(false);
        jspLH.setViewportView(tbChiTiet);

        btnChiTietLop.setBackground(new java.awt.Color(239, 158, 154));
        btnChiTietLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChiTietLop.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lich su 3.png"))); // NOI18N
        btnChiTietLop.setText("CHUYỂN LỚP");
        btnChiTietLop.setActionCommand("");
        btnChiTietLop.setContentAreaFilled(false);
        btnChiTietLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiTietLop.setFocusable(false);
        btnChiTietLop.setOpaque(true);
        btnChiTietLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietLopActionPerformed(evt);
            }
        });

        btnXoaLop.setBackground(new java.awt.Color(239, 158, 154));
        btnXoaLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLop.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnXoaLop.setText("XÓA KHỎI LỚP");
        btnXoaLop.setContentAreaFilled(false);
        btnXoaLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaLop.setFocusable(false);
        btnXoaLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setOpaque(true);
        btnXoaLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnXoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopActionPerformed(evt);
            }
        });

        btnUpdateLop.setBackground(new java.awt.Color(239, 158, 154));
        btnUpdateLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateLop.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cap nhat 1.png"))); // NOI18N
        btnUpdateLop.setText("CẬP NHẬT BẢNG ĐIỂM");
        btnUpdateLop.setContentAreaFilled(false);
        btnUpdateLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateLop.setFocusable(false);
        btnUpdateLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.setOpaque(true);
        btnUpdateLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLopActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("LỚP AV1 - 12343432");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("<KHU VỰC THÔNG TIN LỚP HỌC>");

        javax.swing.GroupLayout pnLopLayout = new javax.swing.GroupLayout(pnLop);
        pnLop.setLayout(pnLopLayout);
        pnLopLayout.setHorizontalGroup(
            pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopLayout.createSequentialGroup()
                .addGap(527, 527, 527)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopLayout.createSequentialGroup()
                .addContainerGap(578, Short.MAX_VALUE)
                .addComponent(btnUpdateLop, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(btnChiTietLop)
                .addGap(54, 54, 54)
                .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jspLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );
        pnLopLayout.setVerticalGroup(
            pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnLopLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jTextArea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(jspLH, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnUpdateLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnChiTietLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))
                    .addGroup(pnLopLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        new FormThemVaoLop().show();
    }//GEN-LAST:event_btnThemLopActionPerformed

    private void btnChiTietLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietLopActionPerformed
        new FormChuyenLop().show();
    }//GEN-LAST:event_btnChiTietLopActionPerformed

    private void btnXoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaLopActionPerformed

    private void btnUpdateLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLopActionPerformed
        new FormCapNhatBangDiem().show();
    }//GEN-LAST:event_btnUpdateLopActionPerformed

    private void btnThemLopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThemLopMouseClicked
        
    }//GEN-LAST:event_btnThemLopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UI_ChiTietLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UI_ChiTietLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UI_ChiTietLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UI_ChiTietLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UI_ChiTietLop().setVisible(true);
            }
        });
    }
    //biến tự định nghĩa
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietLop;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnUpdateLop;
    private javax.swing.JButton btnXoaLop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane jspLH;
    private javax.swing.JPanel pnLop;
    public static javax.swing.JTable tbChiTiet;
    // End of variables declaration//GEN-END:variables
}
