/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LopHoc;

import BUS.bus_LopHoc;
import DTO.dto_ChuongTrinh;
import DTO.dto_LopHoc;
import UI.DangNhap.UI_DangNhap;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FormCapNhatLop extends javax.swing.JFrame {

    /**
     * Creates new form FormCapNhatLop
     */
    
    private dto_LopHoc lopChon;
    
    public FormCapNhatLop() {
        initComponents();
    }
    
    public FormCapNhatLop(dto_LopHoc lopChon){
        initComponents();
        this.lopChon = new dto_LopHoc();
        this.lopChon = lopChon;
        
        setGiaoDienBanDau();
    }
    
    DefaultComboBoxModel dfcbChuongTrinh;
    ArrayList<dto_ChuongTrinh> dsChuongTrinh;
    ArrayList<dto_LopHoc> dsLopHoc;

    // HÀM CẬP NHẬT THÔNG TIN
    public void capNhatLop() {

        dto_LopHoc lop = new dto_LopHoc();
        lop = layThongTinNhap();

        if (lop != null) {
            int rs = new bus_LopHoc().capNhatLop(lop);

            if (rs == 0) {
                JOptionPane.showMessageDialog(null, "Không thành công");
            } else {
                this.dispose();
                JOptionPane.showMessageDialog(null, "Cập Nhật Hoàn Tất");
                UI_LopHoc.hienThiDsLop();
            }
        }

    }
            
    
    // HÀM LẤY THÔNG TIN NHẬP & KIỂM TRA DỮ LIỆU & TRẢ VỀ ĐỐI TƯỢNG LỚP HỌC
    public dto_LopHoc layThongTinNhap(){
        
        dto_LopHoc lop = null;
        
        String tenLop = txtTenLop.getText();
        String strSoBuoi = txtSoBuoi.getText();
        
        Date ngayBd = dateNgayBatDau.getDate();
        
        dto_ChuongTrinh ct = (dto_ChuongTrinh)cbChuongTrinh.getSelectedItem();
        
        if(tenLop.isEmpty() || strSoBuoi.isEmpty() || ngayBd == null || ct == null){
            JOptionPane.showMessageDialog(null, "Chưa Nhập Đủ Thông Tin");
            return null;
        }
        
        int soBuoi=0;
        try{
            soBuoi = Integer.parseInt(strSoBuoi);
            
        }catch(Exception ex){
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, "Số Buổi Không Hợp Lệ");
            return null;
        }
        
        lop = new dto_LopHoc();
        lop.setMaLop(this.lopChon.getMaLop());
        lop.setMaCt(ct.getMaCt());
        lop.setTenLop(tenLop);
        lop.setSoBuoi(soBuoi);
        lop.setNgayBd(ngayBd);
        
        if(ckDongLop.isSelected())
            lop.setTrangThai(0);
        else
            lop.setTrangThai(1);
        
        return lop;
    }

    // HÀM SET GIAO DIỆN BAN ĐẦU
    public void setGiaoDienBanDau(){
        dsLopHoc = new ArrayList<dto_LopHoc>();
        dsLopHoc = UI_LopHoc.getDsLopHoc();
        
        dsChuongTrinh = new ArrayList<dto_ChuongTrinh>();
        dsChuongTrinh = new bus_LopHoc().layDsChuongTrinh();
        
        dfcbChuongTrinh = new DefaultComboBoxModel();
        dfcbChuongTrinh.addAll(dsChuongTrinh);
        txtTenLop.setText(this.lopChon.getTenLop());
        txtSoBuoi.setText(this.lopChon.getSoBuoi()+"");
        dateNgayBatDau.setDate(this.lopChon.getNgayBd());
        
        cbChuongTrinh.setModel(dfcbChuongTrinh);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnCapNhatLop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTenLop = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbChuongTrinh = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtSoBuoi = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        dateNgayBatDau = new com.toedter.calendar.JDateChooser();
        btnXacNhan = new javax.swing.JButton();
        ckDongLop = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cập Nhật Lớp");
        setMinimumSize(new java.awt.Dimension(500, 250));
        setPreferredSize(new java.awt.Dimension(500, 250));

        pnCapNhatLop.setBackground(new java.awt.Color(230, 245, 255));
        pnCapNhatLop.setMinimumSize(new java.awt.Dimension(500, 250));

        jLabel1.setText("Tên Lớp");

        txtTenLop.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTenLop.setText("TOEIC 500 - K12");

        jLabel2.setText("Chương Trình");

        cbChuongTrinh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Số Buổi");

        txtSoBuoi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSoBuoi.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoBuoi.setText("15");

        jLabel4.setText("Ngày Bắt Đầu");

        btnXacNhan.setBackground(new java.awt.Color(0, 102, 153));
        btnXacNhan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXacNhan.setForeground(new java.awt.Color(255, 255, 255));
        btnXacNhan.setText("XÁC NHẬN");
        btnXacNhan.setContentAreaFilled(false);
        btnXacNhan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXacNhan.setFocusable(false);
        btnXacNhan.setOpaque(true);
        btnXacNhan.setPreferredSize(new java.awt.Dimension(209, 40));
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        ckDongLop.setText("Đóng Lớp");

        javax.swing.GroupLayout pnCapNhatLopLayout = new javax.swing.GroupLayout(pnCapNhatLop);
        pnCapNhatLop.setLayout(pnCapNhatLopLayout);
        pnCapNhatLopLayout.setHorizontalGroup(
            pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4)
                    .addComponent(dateNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                        .addComponent(txtSoBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ckDongLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(36, 36, 36))
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnCapNhatLopLayout.setVerticalGroup(
            pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnCapNhatLopLayout.createSequentialGroup()
                        .addComponent(txtTenLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnCapNhatLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSoBuoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChuongTrinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ckDongLop, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(dateNgayBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(btnXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnCapNhatLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(516, 289));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed

        capNhatLop();
    }//GEN-LAST:event_btnXacNhanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormCapNhatLop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormCapNhatLop().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> cbChuongTrinh;
    private javax.swing.JCheckBox ckDongLop;
    private com.toedter.calendar.JDateChooser dateNgayBatDau;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel pnCapNhatLop;
    private javax.swing.JTextField txtSoBuoi;
    private javax.swing.JTextField txtTenLop;
    // End of variables declaration//GEN-END:variables
}
