/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LopHoc;
import BUS.bus_LopHoc;
import DTO.dto_LopHoc;
import UI.LopHoc.ChiTietLopHoc.UI_ChiTietLop;
import UI.KhachHang.FormThemKH;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ThinkPro
 */
public class UI_LopHoc extends javax.swing.JPanel {

    /**
     * Creates new form LopHocUI
     */
    public UI_LopHoc() {
        initComponents();
        setupTable();
        hienThiDsLop(0);
    }
   
    // BIẾN TỰ ĐỊNH NGHĨA
    static DefaultTableModel static_dtmLopHoc;
    static ArrayList<dto_LopHoc> static_dsLopHoc;
    
    // HÀM HIỂN THỊ THÔNG TIN LÊN BẢNG
    public static void hienThiDsLop(int trangThai){
        static_dsLopHoc = new bus_LopHoc().layDsLop(trangThai);
        if(static_dsLopHoc != null){
            reloadTable(static_dsLopHoc);
        }
    }
    
    // HÀM LOAD DỮ LIỆU LÊN BẢNG
    public static void reloadTable(ArrayList<dto_LopHoc> dsChuongTrinh) {

        static_dsLopHoc = new ArrayList<dto_LopHoc>();
        static_dsLopHoc = dsChuongTrinh;

        int stt = 0;

        static_dtmLopHoc.setRowCount(0);

        for (dto_LopHoc ct : dsChuongTrinh) {

            stt++;
            Vector<Object> vc = new Vector<Object>();

            vc.add(stt);
            vc.add(ct.getMaLop());
            vc.add(ct.getTenLop());
            vc.add(ct.getTenCt());
            vc.add(ct.getNgayBd());
            vc.add(ct.getNgayKt());
            vc.add(ct.getGiaoVien());
            vc.add(ct.getPhong());
            vc.add(ct.getMaNv());
            vc.add(ct.getTrangThai());


            if (ct.getTrangThai() == 0) {
                vc.add("Đóng");
            } else {
                vc.add("Mở");
            }

            static_dtmLopHoc.addRow(vc);
        }
    }
    // HÀM TẠO BẢNG
    public void setupTable() {
        static_dtmLopHoc = new DefaultTableModel();

        static_dtmLopHoc.addColumn("STT");
        static_dtmLopHoc.addColumn("Mã Lớp");
        static_dtmLopHoc.addColumn("Tên Lớp");
        static_dtmLopHoc.addColumn("Chương Trình");
        static_dtmLopHoc.addColumn("Bắt Đầu");
        static_dtmLopHoc.addColumn("Kết Thúc");
        static_dtmLopHoc.addColumn("Sỉ Số");
        static_dtmLopHoc.addColumn("Giáo Viên");
        static_dtmLopHoc.addColumn("Phòng");
        static_dtmLopHoc.addColumn("Phụ Trách"); 
        static_dtmLopHoc.addColumn("Trạng Thái");

        tbLopHoc.setModel(static_dtmLopHoc);

        tbLopHoc.getColumnModel().getColumn(0).setMaxWidth(50);
        tbLopHoc.getColumnModel().getColumn(1).setMinWidth(80);
        tbLopHoc.getColumnModel().getColumn(1).setMaxWidth(80);
        tbLopHoc.getColumnModel().getColumn(2).setMinWidth(180);
        tbLopHoc.getColumnModel().getColumn(2).setMaxWidth(180);
        tbLopHoc.getColumnModel().getColumn(3).setMinWidth(180);
        tbLopHoc.getColumnModel().getColumn(3).setMaxWidth(180);
        tbLopHoc.getColumnModel().getColumn(4).setMaxWidth(80);
        tbLopHoc.getColumnModel().getColumn(4).setMinWidth(80);
        tbLopHoc.getColumnModel().getColumn(5).setMaxWidth(80);
        tbLopHoc.getColumnModel().getColumn(5).setMinWidth(80);
        tbLopHoc.getColumnModel().getColumn(6).setMinWidth(150);
        tbLopHoc.getColumnModel().getColumn(6).setMaxWidth(150);

 

        tbLopHoc.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        tbLopHoc.getTableHeader().setOpaque(false);
        tbLopHoc.getTableHeader().setForeground(new Color(0, 0, 0));
        tbLopHoc.setSelectionBackground(new Color(0, 64, 128));

    }
    
    // HÀM ẨN CHỨC NĂNG DÀNH CHO GIAO DIỆN GHI DANH
    public void hideBtnLop(){
        btnChiTietLop.setVisible(false);
        btnThemLop.setVisible(false);
        btnCapNhatLop.setVisible(false);
        btnXoaLop.setVisible(false);
    } 
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCapNhatLop = new javax.swing.JButton();
        btnXoaLop = new javax.swing.JButton();
        btnChiTietLop = new javax.swing.JButton();
        lblTimLop = new javax.swing.JLabel();
        txtTimLop = new javax.swing.JTextField();
        jspLH = new javax.swing.JScrollPane();
        tbLopHoc = new javax.swing.JTable();
        btnThemLop = new javax.swing.JButton();
        ckLopDong = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(230, 245, 255));
        setMinimumSize(new java.awt.Dimension(1350, 634));
        setPreferredSize(new java.awt.Dimension(1350, 634));

        btnCapNhatLop.setBackground(new java.awt.Color(230, 245, 255));
        btnCapNhatLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCapNhatLop.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/capnhat.png"))); // NOI18N
        btnCapNhatLop.setContentAreaFilled(false);
        btnCapNhatLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCapNhatLop.setFocusable(false);
        btnCapNhatLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnCapNhatLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnCapNhatLop.setOpaque(true);
        btnCapNhatLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnCapNhatLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatLopActionPerformed(evt);
            }
        });

        btnXoaLop.setBackground(new java.awt.Color(230, 245, 255));
        btnXoaLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLop.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnXoaLop.setContentAreaFilled(false);
        btnXoaLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaLop.setFocusable(false);
        btnXoaLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setOpaque(true);
        btnXoaLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnXoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopActionPerformed(evt);
            }
        });

        btnChiTietLop.setBackground(new java.awt.Color(230, 245, 255));
        btnChiTietLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChiTietLop.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/chitietlop.png"))); // NOI18N
        btnChiTietLop.setToolTipText("Chi Tiết Lớp");
        btnChiTietLop.setBorder(null);
        btnChiTietLop.setContentAreaFilled(false);
        btnChiTietLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiTietLop.setFocusable(false);
        btnChiTietLop.setOpaque(true);
        btnChiTietLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietLopActionPerformed(evt);
            }
        });

        lblTimLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblTimLop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTimLop.setText("Tìm Kiếm");

        txtTimLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimLop.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimLop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        txtTimLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimLopActionPerformed(evt);
            }
        });

        jspLH.setBackground(new java.awt.Color(255, 255, 255));
        jspLH.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspLH.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspLH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jspLH.setPreferredSize(new java.awt.Dimension(469, 400));

        tbLopHoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Lớp", "Tên Lớp", "Tên Chương Trình", "Bắt Đầu", "Kết Thúc", "Số HV", "Giáo Viên", "Phòng", "ID Phụ Trách", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLopHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbLopHoc.setDoubleBuffered(true);
        tbLopHoc.setFocusable(false);
        tbLopHoc.setRowHeight(30);
        tbLopHoc.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbLopHoc.getTableHeader().setReorderingAllowed(false);
        jspLH.setViewportView(tbLopHoc);
        if (tbLopHoc.getColumnModel().getColumnCount() > 0) {
            tbLopHoc.getColumnModel().getColumn(0).setMinWidth(50);
            tbLopHoc.getColumnModel().getColumn(0).setMaxWidth(50);
            tbLopHoc.getColumnModel().getColumn(1).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(1).setMaxWidth(100);
            tbLopHoc.getColumnModel().getColumn(2).setMinWidth(150);
            tbLopHoc.getColumnModel().getColumn(2).setMaxWidth(150);
            tbLopHoc.getColumnModel().getColumn(3).setMinWidth(150);
            tbLopHoc.getColumnModel().getColumn(3).setMaxWidth(150);
            tbLopHoc.getColumnModel().getColumn(4).setMinWidth(80);
            tbLopHoc.getColumnModel().getColumn(4).setMaxWidth(80);
            tbLopHoc.getColumnModel().getColumn(5).setMinWidth(80);
            tbLopHoc.getColumnModel().getColumn(5).setMaxWidth(80);
            tbLopHoc.getColumnModel().getColumn(6).setMinWidth(50);
            tbLopHoc.getColumnModel().getColumn(6).setMaxWidth(50);
            tbLopHoc.getColumnModel().getColumn(8).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(8).setMaxWidth(100);
            tbLopHoc.getColumnModel().getColumn(9).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        btnThemLop.setBackground(new java.awt.Color(230, 245, 255));
        btnThemLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/taomoi.png"))); // NOI18N
        btnThemLop.setContentAreaFilled(false);
        btnThemLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemLop.setFocusable(false);
        btnThemLop.setOpaque(true);
        btnThemLop.setPreferredSize(new java.awt.Dimension(183, 40));
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });

        ckLopDong.setBackground(new java.awt.Color(230, 245, 255));
        ckLopDong.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ckLopDong.setText("Hiển thị lớp đã đóng");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jspLH, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTimLop)
                        .addGap(18, 18, 18)
                        .addComponent(txtTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ckLopDong)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnChiTietLop)
                        .addGap(200, 200, 200)
                        .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCapNhatLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(ckLopDong))
                            .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCapNhatLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnChiTietLop, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jspLH, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCapNhatLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatLopActionPerformed
        new FormCapNhatLH().show();
    }//GEN-LAST:event_btnCapNhatLopActionPerformed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        new FormThemLH().show();
    }//GEN-LAST:event_btnThemLopActionPerformed

    private void btnChiTietLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietLopActionPerformed
        new UI_ChiTietLop().show();
    }//GEN-LAST:event_btnChiTietLopActionPerformed

    private void btnXoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaLopActionPerformed

    private void txtTimLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimLopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhatLop;
    private javax.swing.JButton btnChiTietLop;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnXoaLop;
    private javax.swing.JCheckBox ckLopDong;
    private javax.swing.JScrollPane jspLH;
    private javax.swing.JLabel lblTimLop;
    private javax.swing.JTable tbLopHoc;
    private javax.swing.JTextField txtTimLop;
    // End of variables declaration//GEN-END:variables
}
