/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.LopHocUI;

import UI.LopHocUI.ChiTietLopHoc.UI_ChiTietLop;
import UI.KhachHangUI.FormThemKH;
import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author ThinkPro
 */
public class UI_LopHoc extends javax.swing.JPanel {

    /**
     * Creates new form LopHocUI
     */
    public UI_LopHoc() {
        initComponents();
        tbLopHoc.getTableHeader().setFont(new Font("Tahoma", Font.BOLD, 12));
        tbLopHoc.getTableHeader().setOpaque(false);
        tbLopHoc.getTableHeader().setForeground(new Color(0,0,0));
        tbLopHoc.setSelectionBackground(new Color(204,204,204));
    }
    /** KHU VỰC CỦA TÂN */
   
    // * method hideBtnLop() Ẩn các button trong giao diện lớp học
    public void hideBtnLop(){
        btnChiTietLop.setVisible(false);
        btnThemLop.setVisible(false);
        btnUpdateLop.setVisible(false);
        btnXoaLop.setVisible(false);
    } 
    
    /** HẾT KHU VỰC CỦA BẠN TÂN  */
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnLop = new javax.swing.JPanel();
        lblTimLop = new javax.swing.JLabel();
        txtTimLop = new javax.swing.JTextField();
        btnThemLop = new javax.swing.JButton();
        jspLH = new javax.swing.JScrollPane();
        tbLopHoc = new javax.swing.JTable();
        btnUpdateLop = new javax.swing.JButton();
        btnXoaLop = new javax.swing.JButton();
        btnChiTietLop = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1200, 659));
        setMinimumSize(new java.awt.Dimension(1200, 659));
        setPreferredSize(new java.awt.Dimension(1200, 659));

        pnLop.setBackground(new java.awt.Color(255, 255, 255));

        lblTimLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTimLop.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblTimLop.setText("TÌM LỚP HỌC");

        txtTimLop.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtTimLop.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txtTimLop.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 1, 0, new java.awt.Color(153, 153, 153)));

        btnThemLop.setBackground(new java.awt.Color(0, 102, 153));
        btnThemLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThemLop.setForeground(new java.awt.Color(255, 255, 255));
        btnThemLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/them lop.png"))); // NOI18N
        btnThemLop.setText("TẠO LỚP HỌC MỚI");
        btnThemLop.setContentAreaFilled(false);
        btnThemLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnThemLop.setFocusable(false);
        btnThemLop.setOpaque(true);
        btnThemLop.setPreferredSize(new java.awt.Dimension(183, 40));
        btnThemLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemLopActionPerformed(evt);
            }
        });

        jspLH.setBackground(new java.awt.Color(255, 255, 255));
        jspLH.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jspLH.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        jspLH.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jspLH.setPreferredSize(new java.awt.Dimension(469, 400));

        tbLopHoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbLopHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "1", "a", null, null, null, null, null, null, null, null},
                {null, "2", "a", null, null, null, null, null, null, null, null},
                {null, "3", "a", null, null, null, null, null, null, null, null},
                {null, "4", "a", null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "STT", "Mã Lớp", "Tên Lớp", "Tên Chương Trình", "Bắt Đầu", "Kết Thúc", "Số HV", "Giáo Viên", "Phòng", "ID Phụ Trách", "Trạng Thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbLopHoc.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbLopHoc.setDoubleBuffered(true);
        tbLopHoc.setFocusable(false);
        tbLopHoc.setPreferredSize(new java.awt.Dimension(600, 450));
        tbLopHoc.setRowHeight(30);
        tbLopHoc.setSelectionBackground(new java.awt.Color(232, 57, 95));
        tbLopHoc.getTableHeader().setReorderingAllowed(false);
        jspLH.setViewportView(tbLopHoc);
        if (tbLopHoc.getColumnModel().getColumnCount() > 0) {
            tbLopHoc.getColumnModel().getColumn(0).setMinWidth(50);
            tbLopHoc.getColumnModel().getColumn(0).setMaxWidth(50);
            tbLopHoc.getColumnModel().getColumn(1).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(1).setMaxWidth(100);
            tbLopHoc.getColumnModel().getColumn(2).setMinWidth(150);
            tbLopHoc.getColumnModel().getColumn(2).setMaxWidth(150);
            tbLopHoc.getColumnModel().getColumn(3).setMinWidth(150);
            tbLopHoc.getColumnModel().getColumn(3).setMaxWidth(150);
            tbLopHoc.getColumnModel().getColumn(4).setMinWidth(80);
            tbLopHoc.getColumnModel().getColumn(4).setMaxWidth(80);
            tbLopHoc.getColumnModel().getColumn(5).setMinWidth(80);
            tbLopHoc.getColumnModel().getColumn(5).setMaxWidth(80);
            tbLopHoc.getColumnModel().getColumn(6).setMinWidth(50);
            tbLopHoc.getColumnModel().getColumn(6).setMaxWidth(50);
            tbLopHoc.getColumnModel().getColumn(8).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(8).setMaxWidth(100);
            tbLopHoc.getColumnModel().getColumn(9).setMinWidth(100);
            tbLopHoc.getColumnModel().getColumn(9).setMaxWidth(100);
        }

        btnUpdateLop.setBackground(new java.awt.Color(0, 102, 102));
        btnUpdateLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdateLop.setForeground(new java.awt.Color(255, 255, 255));
        btnUpdateLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cap nhat 1.png"))); // NOI18N
        btnUpdateLop.setText("CẬP NHẬT");
        btnUpdateLop.setContentAreaFilled(false);
        btnUpdateLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUpdateLop.setFocusable(false);
        btnUpdateLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.setOpaque(true);
        btnUpdateLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnUpdateLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateLopActionPerformed(evt);
            }
        });

        btnXoaLop.setBackground(new java.awt.Color(0, 102, 102));
        btnXoaLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXoaLop.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/xoa.png"))); // NOI18N
        btnXoaLop.setText("XÓA");
        btnXoaLop.setContentAreaFilled(false);
        btnXoaLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnXoaLop.setFocusable(false);
        btnXoaLop.setMaximumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setMinimumSize(new java.awt.Dimension(129, 49));
        btnXoaLop.setOpaque(true);
        btnXoaLop.setPreferredSize(new java.awt.Dimension(129, 49));
        btnXoaLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaLopActionPerformed(evt);
            }
        });

        btnChiTietLop.setBackground(new java.awt.Color(0, 102, 102));
        btnChiTietLop.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnChiTietLop.setForeground(new java.awt.Color(255, 255, 255));
        btnChiTietLop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/lich su 3.png"))); // NOI18N
        btnChiTietLop.setText("QUẢN LÝ LỚP");
        btnChiTietLop.setActionCommand("");
        btnChiTietLop.setContentAreaFilled(false);
        btnChiTietLop.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChiTietLop.setFocusable(false);
        btnChiTietLop.setOpaque(true);
        btnChiTietLop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietLopActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnLopLayout = new javax.swing.GroupLayout(pnLop);
        pnLop.setLayout(pnLopLayout);
        pnLopLayout.setHorizontalGroup(
            pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnLopLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnLopLayout.createSequentialGroup()
                        .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnLopLayout.createSequentialGroup()
                                .addComponent(btnChiTietLop)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnUpdateLop, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addComponent(jspLH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))
                    .addGroup(pnLopLayout.createSequentialGroup()
                        .addComponent(lblTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(txtTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                        .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72))))
        );
        pnLopLayout.setVerticalGroup(
            pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnLopLayout.createSequentialGroup()
                .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTimLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jspLH, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnLopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoaLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChiTietLop, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnLop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateLopActionPerformed
        new FormCapNhatLH().show();
    }//GEN-LAST:event_btnUpdateLopActionPerformed

    private void btnThemLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemLopActionPerformed
        new FormThemLH().show();
    }//GEN-LAST:event_btnThemLopActionPerformed

    private void btnChiTietLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietLopActionPerformed
        new UI_ChiTietLop().show();
    }//GEN-LAST:event_btnChiTietLopActionPerformed

    private void btnXoaLopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaLopActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnXoaLopActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChiTietLop;
    private javax.swing.JButton btnThemLop;
    private javax.swing.JButton btnUpdateLop;
    private javax.swing.JButton btnXoaLop;
    private javax.swing.JScrollPane jspLH;
    private javax.swing.JLabel lblTimLop;
    private javax.swing.JPanel pnLop;
    private javax.swing.JTable tbLopHoc;
    private javax.swing.JTextField txtTimLop;
    // End of variables declaration//GEN-END:variables
}
